# Generated by Django 3.0.5 on 2021-11-28 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VIEW_COMISSAO_MALETA',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('id_maleta', models.CharField(max_length=20)),
                ('nome_maleta', models.CharField(max_length=30)),
                ('vendedor', models.CharField(max_length=20)),
                ('nome_vendedor', models.CharField(max_length=20)),
                ('valor_comissao', models.DecimalField(decimal_places=0, max_digits=3)),
            ],
            options={
                'db_table': 'VIEW_COMISSAO_MALETA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VIEW_PRODUTOS',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cod_produto', models.CharField(max_length=20)),
                ('des_produto', models.CharField(max_length=100)),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('colecao', models.CharField(blank=True, max_length=30, null=True)),
                ('qtde_estoque', models.IntegerField()),
                ('dt_insercao', models.DateField(auto_now_add=True)),
                ('cat_id', models.IntegerField()),
                ('des_categoria', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'VIEW_PRODUTOS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('des_categoria', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='ComissaoMaletaVendedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_maleta', models.IntegerField()),
                ('vendedor', models.CharField(max_length=20)),
                ('valor_comissao', models.DecimalField(decimal_places=0, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='Maleta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_maleta', models.CharField(max_length=30)),
                ('faixa_inicial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('faixa_final', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_produto', models.CharField(max_length=20)),
                ('des_produto', models.CharField(max_length=100)),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('colecao', models.CharField(blank=True, max_length=30, null=True)),
                ('qtde_estoque', models.IntegerField()),
                ('dt_insercao', models.DateField(auto_now_add=True)),
                ('cod_categoria', models.IntegerField()),
            ],
        ),
    ]
