# Generated by Django 3.0.5 on 2021-12-04 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='id_fornecedor',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
