# Generated by Django 3.0.5 on 2021-12-04 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_produto_id_fornecedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='valor_custo',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=10),
            preserve_default=False,
        ),
    ]
