# Generated by Django 3.0.5 on 2021-12-04 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_produto_valor_custo'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaletaAberta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendedor', models.CharField(max_length=30)),
                ('id_maleta', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MaletaAbertaProdutos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_maletaberta', models.IntegerField()),
                ('cod_produto', models.CharField(max_length=50)),
                ('quantidade', models.IntegerField()),
            ],
        ),
    ]
