# Generated by Django 3.0.5 on 2021-12-04 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0006_maletaabertaprodutos_qtde_vendida'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maletaabertaprodutos',
            old_name='id_maletaberta',
            new_name='id_maletaaberta',
        ),
    ]
