# Generated by Django 3.0.5 on 2021-12-04 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0007_auto_20211204_0533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maletaabertaprodutos',
            name='qtde_vendida',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
