# Generated by Django 3.0.5 on 2021-12-05 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0009_view_maleta_produtos'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='img_produto',
            field=models.FileField(blank=True, null=True, upload_to='produtos/produtos.images'),
        ),
    ]
