# Generated by Django 3.0.5 on 2021-12-05 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0010_produto_img_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='valor_custo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
