# Generated by Django 3.0.5 on 2021-11-26 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VIEW_USUARIOS_GRUPO',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=20)),
                ('grupo', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'VIEW_USUARIOS_GRUPO',
                'managed': False,
            },
        ),
    ]
