# Generated by Django 3.0.5 on 2021-11-27 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_cliente_vendedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='whatsapp',
            field=models.CharField(max_length=3),
        ),
    ]
