# Generated by Django 3.0.5 on 2021-11-27 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_auto_20211127_0002'),
    ]

    operations = [
        migrations.CreateModel(
            name='VIEW_VENDEDORES',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('nome_vendedor', models.CharField(max_length=100)),
                ('cpf_cnpj', models.CharField(max_length=50)),
                ('rg', models.CharField(max_length=20)),
                ('endereco', models.CharField(max_length=200)),
                ('bairro', models.CharField(max_length=50)),
                ('cidade', models.CharField(max_length=30)),
                ('estado', models.CharField(max_length=2)),
                ('cep', models.CharField(max_length=20)),
                ('telefone', models.CharField(max_length=20)),
                ('id_maleta', models.IntegerField()),
                ('nome_maleta', models.CharField(max_length=30)),
                ('ref1_empresa', models.CharField(max_length=50)),
                ('ref1_contato', models.CharField(max_length=30)),
                ('ref1_telefone', models.CharField(max_length=20)),
                ('ref2_empresa', models.CharField(max_length=50)),
                ('ref2_contato', models.CharField(max_length=30)),
                ('ref2_telefone', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'VIEW_VENDEDORES',
                'managed': False,
            },
        ),
    ]
