from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .classes import password_reset, password_reset_done, password_reset_confirm, password_reset_complete
from . import views

urlpatterns = [
    path('', views.home, name="home"),
    path('login', views.login, name="login"),
    path('logout', views.user_logout, name="user_logout"),
    path('resetPassword/', password_reset, name="resetPassword"),
    path('definirComissao', views.definirComissao, name="definirComissao"),
    path('filtrarVendedor', views.filtrarVendedor, name="filtrarVendedor"),
    path('filtrarMaleta', views.filtrarMaleta, name="filtrarMaleta"),
    path('definicaoComissao', views.definicaoComissao, name="definicaoComissao"),
    path('listarComissoes', views.listarComissoes, name="listarComissoes"),
    path('filtrarComissoes', views.filtrarComissoes, name="filtrarComissoes"),
    path('editarComissao/<int:com_id>/', views.editarComissao, name="editarComissao"),
    path('alterarComissao/<int:com_id>/', views.alterarComissao, name="alterarComissao"),
    path('deletarComissao/<int:com_id>/', views.deletarComissao, name="deletarComissao"),
    path('registrarVenda', views.registrarVenda, name="registrarVenda"),
    path('adicionarProduto/<int:venda_id>/', views.adicionarProduto, name="adicionarProduto"),
    path('filtrarProduto/<int:venda_id>/', views.filtrarProduto, name="filtrarProduto"),
    path('adicionarProdutoVenda', views.adicionarProdutoVenda, name="adicionarProdutoVenda"),
    path('incluirProdutoVenda', views.incluirProdutoVenda, name="incluirProdutoVenda"),
    path('filtrarClienteVenda', views.filtrarClienteVenda, name="filtrarClienteVenda"),
    path('filtrarCliente', views.filtrarCliente, name="filtrarCliente"),
    path('efetuarRegistroVenda', views.efetuarRegistroVenda, name="efetuarRegistroVenda"),
    path('registrarPagamento', views.registrarPagamento, name="registrarPagamento"),
    path('filtrarClienteProduto', views.filtrarClienteProduto, name="filtrarClienteProduto"),
    path('efetuarPagamento/<int:venda_id>/<int:parcela>/', views.efetuarPagamento, name="efetuarPagamento"),
    path('efetivarPagamento', views.efetivarPagamento, name="efetivarPagamento"),
    path('deletarPagamento/<int:venda_id>/<int:parcela>/', views.deletarPagamento, name="deletarPagamento"),
    path('relatorioFluxoCaixaAdmin', views.relatorioFluxoCaixaAdmin, name="relatorioFluxoCaixaAdmin"),
    path('relatorioFluxoCaixaVendedor', views.relatorioFluxoCaixaVendedor, name="relatorioFluxoCaixaVendedor"),
    path('listarClienteProduto', views.listarClienteProduto, name="listarClienteProduto"),
    path('listarClienteProdutoAdmin', views.listarClienteProdutoAdmin, name="listarClienteProdutoAdmin"),
    path('relatorioFluxoCaixaMensal', views.relatorioFluxoCaixaMensal, name="relatorioFluxoCaixaMensal"),
    path('filtrarMes', views.filtrarMes, name="filtrarMes"),
    path('filtrarAno', views.filtrarAno, name="filtrarAno"),
    path('relatorioFluxoCaixaAnual', views.relatorioFluxoCaixaAnual, name="relatorioFluxoCaixaAnual"),
    path('cadastrarFornecedor', views.cadastrarFornecedor, name="cadastrarFornecedor"),
    path('listarFornecedores', views.listarFornecedores, name="listarFornecedores"),
    path('efetuarCadastroFornecedor', views.efetuarCadastroFornecedor, name="efetuarCadastroFornecedor"),
    path('filtrarFornecedor', views.filtrarFornecedor, name="filtrarFornecedor"),
    path('editarFornecedor/<int:forn_id>/', views.editarFornecedor, name="editarFornecedor"),
    path('alterarFornecedor/<int:forn_id>/', views.alterarFornecedor, name="alterarFornecedor"),
    path('deletarFornecedor/<int:forn_id>/', views.deletarFornecedor, name="deletarFornecedor"),
    path('listarClienteVendedor', views.listarClienteVendedor, name="listarClienteVendedor"),
    path('inicioVendaVendedor', views.inicioVendaVendedor, name="inicioVendaVendedor"),
    path('efetivarVendaVendedor', views.efetivarVendaVendedor, name="efetivarVendaVendedor"),
    path('filtrarClienteVendedor', views.filtrarClienteVendedor, name="filtrarClienteVendedor"),
    path('incluirProdutoVendaVendedor', views.incluirProdutoVendaVendedor, name="incluirProdutoVendaVendedor"),
    path('adicionarProdutoVendedor/<int:venda_id>/<str:cod_produto>/', views.adicionarProdutoVendedor, name="adicionarProdutoVendedor"),
    path('adicionarProdutoVendaVendedor', views.adicionarProdutoVendaVendedor, name="adicionarProdutoVendaVendedor")
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
