# Generated by Django 3.0.5 on 2021-11-28 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VIEW_FLUXO_CAIXA',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('dt_venda', models.DateField()),
                ('hr_venda', models.TimeField()),
                ('nome_cliente', models.CharField(max_length=100)),
                ('cod_produto', models.CharField(max_length=30)),
                ('des_produto', models.CharField(max_length=100)),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantidade', models.IntegerField()),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vendedor', models.CharField(max_length=30)),
                ('nome_vendedor', models.CharField(max_length=100)),
                ('comissao', models.DecimalField(decimal_places=0, max_digits=3)),
                ('valor_comissao', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qtde_parcelas', models.CharField(max_length=1)),
                ('valor_custo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lucro', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_total_venda', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'VIEW_FLUXO_CAIXA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VIEW_VENDAS_PARCELAS',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('dt_venda', models.DateField()),
                ('nome_cliente', models.CharField(max_length=100)),
                ('cod_produto', models.CharField(max_length=30)),
                ('des_produto', models.CharField(max_length=100)),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantidade', models.IntegerField()),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('parcela', models.IntegerField()),
                ('valor_pago', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_total_pago', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'VIEW_VENDAS_PARCELAS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_venda', models.DateField()),
                ('hr_venda', models.TimeField()),
                ('nome_cliente', models.CharField(max_length=100)),
                ('cod_produto', models.CharField(max_length=30)),
                ('quantidade', models.IntegerField()),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_custo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vendedor', models.CharField(max_length=30)),
                ('tipo_pagamento', models.CharField(max_length=50)),
                ('tipo_venda', models.CharField(max_length=10)),
                ('qtde_parcelas', models.CharField(max_length=1)),
                ('valor_pago', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='VendaPagamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_venda', models.IntegerField()),
                ('parcela', models.IntegerField()),
                ('valor_pago', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
