# Generated by Django 3.0.5 on 2021-11-28 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendaProduto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_venda', models.IntegerField()),
                ('cod_produto', models.CharField(max_length=30)),
                ('quantidade', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='venda',
            name='cod_produto',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='quantidade',
        ),
    ]
