# Generated by Django 3.0.5 on 2021-11-28 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0002_auto_20211128_0235'),
    ]

    operations = [
        migrations.CreateModel(
            name='VIEW_VENDAS_PENDENTES',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('dt_venda', models.DateField()),
                ('hr_venda', models.TimeField()),
                ('nome_cliente', models.CharField(max_length=100)),
                ('cod_produto', models.CharField(max_length=30)),
                ('des_produto', models.CharField(max_length=100)),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantidade', models.IntegerField()),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vendedor', models.CharField(max_length=30)),
                ('nome_vendedor', models.CharField(max_length=100)),
                ('qtde_parcelas', models.CharField(max_length=1)),
                ('valor_custo', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'VIEW_VENDAS_PENDENTES',
                'managed': False,
            },
        ),
    ]
