# Generated by Django 3.0.5 on 2021-12-04 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0003_view_vendas_pendentes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_fornecedor', models.CharField(max_length=50)),
                ('endereco', models.CharField(blank=True, max_length=200, null=True)),
                ('cidade', models.CharField(blank=True, max_length=30, null=True)),
                ('telefone', models.CharField(max_length=20)),
                ('contato', models.CharField(max_length=50)),
            ],
        ),
    ]
